service:
  name: empresa

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

package:
  excludeDevDependencies: true
  exclude:
    - test/**

custom:
  stage: ${opt:stage, self:provider.stage}
  config: ${file(../var/${self:custom.stage}.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DynamoTable: ${self:custom.config.AppName}-${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DynamoTable}"
          
functions:
  main:
    handler: main.handler
    events:
      - http:
          method: POST
          path: /
      - http:
          path: /{id}
          method: GET
      - http:
          path: /{id}
          method: PUT
      - http:
          path: /{id}
          method: DELETE
      - http:
          path: /{id}
          method: PATCH

resources:
  Resources:
    MainTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.config.DynamoCapacity}
        TableName: ${self:provider.environment.DynamoTable}
